### ISSUE TITLE
Unable to update environment order

### ISSUE THREAD

**Issue by opendba** [configcat/terraform-provider-configcat#34] opened 2024-01-22 21:47 UTC
### Describe the bug

I have prepared a terraform definition with creation of our product & environment using new property order to specify order for each environments within the product.
After a while, I've decided to change an order of the environments, but each time I apply it tries to change order which doesn't seem to be working.

### To reproduce

```
data "configcat_organizations" "cc_organizations" {
  name_filter_regex = "Digital"
}

resource "configcat_product" "cc_product" {
  name            = "tf-test-product-1"
  organization_id = data.configcat_organizations.cc_organizations.organizations[0].organization_id
  order = 100
}

locals {
  # step 1 - first run create this order
  #  environment_names = ["cc_env2", "cc_env4", "cc_env3", "cc_env1", "prod"]
  # step 2 - second run try to change order of environments
  environment_names = sort(["cc_env2", "cc_env4", "cc_env3", "cc_env1", "prod"])

  cc_environments = {
    for index, name in local.environment_names :
    name => {
      name: name,
      order: index
    }
  }

}

resource "configcat_environment" "cc_environment" {
  for_each = local.cc_environments

  name       = each.key
  product_id = configcat_product.cc_product.id
  order = each.value.order
}
```

### Expected behavior

Order is updated

#### Run to modify environment order

```
$ terraform apply
data.configcat_organizations.cc_organizations: Reading...
data.configcat_organizations.cc_organizations: Read complete after 0s [id=1705959487]
configcat_product.cc_product: Refreshing state... [id=08dc1b73-d783-43a1-8574-26a920ef5845]
configcat_environment.cc_environment["cc_env2"]: Refreshing state... [id=08dc1b73-d7d8-4d13-8b6a-0b8b7356b010]
configcat_environment.cc_environment["cc_env4"]: Refreshing state... [id=08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2]
configcat_environment.cc_environment["prod"]: Refreshing state... [id=08dc1b73-d7b4-4ad8-845e-12bcd679d65b]
configcat_environment.cc_environment["cc_env3"]: Refreshing state... [id=08dc1b73-d7b3-4a46-82b7-fc933c25b7b4]
configcat_environment.cc_environment["cc_env1"]: Refreshing state... [id=08dc1b73-d7a9-4d70-80db-bd49d432be90]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # configcat_environment.cc_environment["cc_env1"] will be updated in-place
  ~ resource "configcat_environment" "cc_environment" {
        id         = "08dc1b73-d7a9-4d70-80db-bd49d432be90"
        name       = "cc_env1"
      ~ order      = 3 -> 0
        # (1 unchanged attribute hidden)
    }

  # configcat_environment.cc_environment["cc_env2"] will be updated in-place
  ~ resource "configcat_environment" "cc_environment" {
        id         = "08dc1b73-d7d8-4d13-8b6a-0b8b7356b010"
        name       = "cc_env2"
      ~ order      = 0 -> 1
        # (1 unchanged attribute hidden)
    }

  # configcat_environment.cc_environment["cc_env4"] will be updated in-place
  ~ resource "configcat_environment" "cc_environment" {
        id         = "08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2"
        name       = "cc_env4"
      ~ order      = 1 -> 3
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

configcat_environment.cc_environment["cc_env4"]: Modifying... [id=08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2]
configcat_environment.cc_environment["cc_env1"]: Modifying... [id=08dc1b73-d7a9-4d70-80db-bd49d432be90]
configcat_environment.cc_environment["cc_env2"]: Modifying... [id=08dc1b73-d7d8-4d13-8b6a-0b8b7356b010]
configcat_environment.cc_environment["cc_env1"]: Modifications complete after 0s [id=08dc1b73-d7a9-4d70-80db-bd49d432be90]
configcat_environment.cc_environment["cc_env4"]: Modifications complete after 0s [id=08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2]
configcat_environment.cc_environment["cc_env2"]: Modifications complete after 0s [id=08dc1b73-d7d8-4d13-8b6a-0b8b7356b010]

Apply complete! Resources: 0 added, 3 changed, 0 destroyed.
```

#### Another run to modify environment order

```
$ terraform apply
data.configcat_organizations.cc_organizations: Reading...
data.configcat_organizations.cc_organizations: Read complete after 0s [id=1705959834]
configcat_product.cc_product: Refreshing state... [id=08dc1b73-d783-43a1-8574-26a920ef5845]
configcat_environment.cc_environment["cc_env2"]: Refreshing state... [id=08dc1b73-d7d8-4d13-8b6a-0b8b7356b010]
configcat_environment.cc_environment["cc_env1"]: Refreshing state... [id=08dc1b73-d7a9-4d70-80db-bd49d432be90]
configcat_environment.cc_environment["cc_env3"]: Refreshing state... [id=08dc1b73-d7b3-4a46-82b7-fc933c25b7b4]
configcat_environment.cc_environment["prod"]: Refreshing state... [id=08dc1b73-d7b4-4ad8-845e-12bcd679d65b]
configcat_environment.cc_environment["cc_env4"]: Refreshing state... [id=08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # configcat_environment.cc_environment["cc_env1"] will be updated in-place
  ~ resource "configcat_environment" "cc_environment" {
        id         = "08dc1b73-d7a9-4d70-80db-bd49d432be90"
        name       = "cc_env1"
      ~ order      = 3 -> 0
        # (1 unchanged attribute hidden)
    }

  # configcat_environment.cc_environment["cc_env2"] will be updated in-place
  ~ resource "configcat_environment" "cc_environment" {
        id         = "08dc1b73-d7d8-4d13-8b6a-0b8b7356b010"
        name       = "cc_env2"
      ~ order      = 0 -> 1
        # (1 unchanged attribute hidden)
    }

  # configcat_environment.cc_environment["cc_env4"] will be updated in-place
  ~ resource "configcat_environment" "cc_environment" {
        id         = "08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2"
        name       = "cc_env4"
      ~ order      = 1 -> 3
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

configcat_environment.cc_environment["cc_env1"]: Modifying... [id=08dc1b73-d7a9-4d70-80db-bd49d432be90]
configcat_environment.cc_environment["cc_env2"]: Modifying... [id=08dc1b73-d7d8-4d13-8b6a-0b8b7356b010]
configcat_environment.cc_environment["cc_env4"]: Modifying... [id=08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2]
configcat_environment.cc_environment["cc_env2"]: Modifications complete after 0s [id=08dc1b73-d7d8-4d13-8b6a-0b8b7356b010]
configcat_environment.cc_environment["cc_env1"]: Modifications complete after 0s [id=08dc1b73-d7a9-4d70-80db-bd49d432be90]
configcat_environment.cc_environment["cc_env4"]: Modifications complete after 0s [id=08dc1b73-d7b3-4a4e-8eeb-b08aa1bad5d2]

Apply complete! Resources: 0 added, 3 changed, 0 destroyed.
```

#### Order of environments from dashboard

<img width="1789" alt="image" src="https://github.com/configcat/terraform-provider-configcat/assets/6765564/d6251cd8-6187-4c3e-83a1-26624024cdf0">

**Comment by laliconfigcat** [comment] 2024-01-23 09:28
Hello @opendba ,

Thanks for reporting the issue. I already found the root cause and working on the fix. It will be released today.

**Closed** 2024-01-23 09:54 UTC
Labels: bug

**Comment by opendba** [comment] 2024-01-23 10:22
Worked as expected after upgrade to 3.1

**Comment by laliconfigcat** [comment] 2024-01-23 10:35
Thanks for checking it and thanks again for reporting the issue. Have a nice day!
